# Generated by Django 3.2.4 on 2021-08-28 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapterID', models.CharField(max_length=255, unique=True, verbose_name='章节编号')),
                ('ChapterName', models.CharField(blank=True, max_length=255, null=True, verbose_name='章节名称')),
                ('ChapterURL', models.CharField(blank=True, max_length=255, null=True, verbose_name='章节存放地址')),
            ],
            options={
                'verbose_name': '章节管理',
                'verbose_name_plural': '章节管理',
            },
        ),
        migrations.CreateModel(
            name='LearnerLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='学习状态')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonID', models.CharField(max_length=255, unique=True, verbose_name='课程编号')),
                ('LessonName', models.CharField(max_length=255, verbose_name='课程名称')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述信息')),
                ('learners', models.ManyToManyField(related_name='subjects', through='lesson.LearnerLesson', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程管理',
                'verbose_name_plural': '课程管理',
            },
        ),
        migrations.AddField(
            model_name='learnerlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.CreateModel(
            name='LearnerChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='学习状态')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.chapter')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.chapter')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='lesson.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='learners',
            field=models.ManyToManyField(related_name='chapters', through='lesson.LearnerChapter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lessons',
            field=models.ManyToManyField(related_name='chapters', through='lesson.ChapterLesson', to='lesson.Lesson', verbose_name='章节所属课程'),
        ),
    ]
