# Generated by Django 3.2.4 on 2021-08-28 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='learners',
            field=models.ManyToManyField(related_name='lessons', through='lesson.LearnerLesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
