# Generated by Django 3.2.4 on 2021-08-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_learners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
    ]
