# Generated by Django 3.2.4 on 2021-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20210828_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterlesson',
            options={'verbose_name': '课程-章节', 'verbose_name_plural': '课程-章节'},
        ),
        migrations.AlterModelOptions(
            name='learnerchapter',
            options={'verbose_name': '学员-章节', 'verbose_name_plural': '学员-章节'},
        ),
        migrations.AlterModelOptions(
            name='learnerlesson',
            options={'verbose_name': '学员-课程', 'verbose_name_plural': '学员-课程'},
        ),
        migrations.AlterField(
            model_name='learnerchapter',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='学习状态'),
        ),
    ]
