# Generated by Django 3.2.4 on 2021-08-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20210828_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlesson',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='lesson.chapter'),
        ),
    ]
