# Generated by Django 3.2.4 on 2021-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='科目名称')),
                ('details', models.CharField(max_length=100, verbose_name='科目详情')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('pre_lesson', models.CharField(default='', max_length=20, verbose_name='前置科目')),
            ],
        ),
    ]
