# Generated by Django 3.2.4 on 2021-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20211019_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='ChapterURL',
        ),
        migrations.AddField(
            model_name='chapter',
            name='ChapterFile',
            field=models.FileField(blank=True, null=True, upload_to='lesson/%Y%m%d/', verbose_name='章节视频'),
        ),
    ]
