# Generated by Django 3.2.4 on 2021-10-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20211019_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='lessons',
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='lesson.lesson', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='prevChapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.chapter', verbose_name='上一章节'),
        ),
        migrations.DeleteModel(
            name='ChapterLesson',
        ),
    ]
