# Generated by Django 3.2.4 on 2021-09-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='按钮名称')),
                ('value', models.CharField(max_length=32, verbose_name='权限值')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='菜单图标地址')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由地址')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='按钮名')),
                ('value', models.CharField(max_length=128, verbose_name='权限值')),
                ('url', models.CharField(max_length=128, verbose_name='接口地址')),
                ('method', models.IntegerField(blank=True, choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'DELETE')], default=0, null=True, verbose_name='请求方法')),
                ('menu', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='岗位名称')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('menus', models.ManyToManyField(to='rbac.Menu', verbose_name='角色所有菜单')),
                ('permissions', models.ManyToManyField(to='rbac.MenuButton', verbose_name='角色所有权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_dept', to='rbac.dept', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户姓名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮件地址')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='个人照片')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.dept', verbose_name='所属部门')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.post', verbose_name='所属岗位')),
                ('roles', models.ManyToManyField(db_constraint=False, to='rbac.Role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['name'],
            },
        ),
    ]
