# Generated by Django 3.2.4 on 2021-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterModelTable(
            name='menubutton',
            table='menu_button',
        ),
    ]
