# Generated by Django 3.2.4 on 2021-09-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210924_1653'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menubutton',
            table='rbac_menu_button',
        ),
    ]
