# Generated by Django 3.2.4 on 2021-08-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
    ]
