# Generated by Django 3.2.4 on 2021-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_menubutton_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(db_constraint=False, to='rbac.Menu', verbose_name='角色所有菜单'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(db_constraint=False, to='rbac.MenuButton', verbose_name='角色所有权限'),
        ),
    ]
