# Generated by Django 3.2.4 on 2021-08-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20210828_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '岗位', 'verbose_name_plural': '岗位'},
        ),
    ]
