# Generated by Django 3.2.4 on 2021-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20210902_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='前端路由path'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标地址'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='接口URL'),
        ),
    ]
