# Generated by Django 3.2.4 on 2021-09-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_user_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='icon',
            new_name='avatar',
        ),
    ]
