# Generated by Django 3.2.4 on 2021-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20210907_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='部门名称'),
        ),
    ]
