# Generated by Django 3.2.4 on 2021-09-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_alter_dept_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='parentDept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.dept', verbose_name='上级部门'),
        ),
    ]
