# Generated by Django 3.2.4 on 2021-09-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0014_alter_dept_parentdept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='parentDept',
            new_name='parent',
        ),
    ]
