# Generated by Django 3.2.4 on 2021-09-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0015_rename_parentdept_dept_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.dept', verbose_name='上级部门'),
        ),
    ]
