# Generated by Django 3.2.4 on 2021-07-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(default=0, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='0', max_length=20, verbose_name='电话号码'),
        ),
    ]
