# Generated by Django 3.2.4 on 2021-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210708_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(default=0, verbose_name='用户组'),
        ),
    ]
