# Generated by Django 3.2.3 on 2021-06-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='subjectManagement_subject',
        ),
    ]
