# Generated by Django 3.2.4 on 2021-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectManagement', '0002_alter_subject_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pre_lesson',
            field=models.CharField(default='', max_length=20, verbose_name='前置科目'),
        ),
    ]
